version: '3.0'
services:
  react-app:
    build: client
    image: react-cli
    container_name: react-cli
    volumes:
      - .:/app
    ports: 
      - 3000:3000
  express-app:
    build: server
    ports: 
      - 5000:5000
    links:
      - database
  database:
      image: "mongo"
      ports: 
        - "27017:27017"
      image: "firestore"
      ports: 
        - "8000:8000"


