version: '1'
services:
  react-app:
    container_name: react-app
    image: react-app
    build: ./react-app
    command: serve -s build
    environment: 
      NODE_ENV: production
    ports: 
      - 3000:3000
  express-app:
    container_name: express-app
    image: express-app
    build: ./express-app
    command: node server.js
    ports: 
      - 5000:5000
    depends_on:
      - "mongo"
    mongo:
      container_name: mongo
      image: "mongo"
      ports: 
        - "27017:27017"
    adminmongo:
      container_name: mongo
      image: "mongo"
      ports: 
        - "27017:27017"


